"""Make FacultyID nullable and add MaxMembers to Groups

Revision ID: e939abc6398e
Revises: 
Create Date: 2026-05-06 14:37:18.816177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e939abc6398e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Faculty', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('GroupType', schema=None) as batch_op:
        batch_op.alter_column('Type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('Groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MaxMembers', sa.Integer(), nullable=True))
        batch_op.alter_column('Description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('CreationDate',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_DATE)'))
        batch_op.alter_column('GroupName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'GroupType', ['GroupTypeID'], ['GroupTypeID'])
        batch_op.create_foreign_key(None, 'Unit', ['UnitID'], ['UnitID'])

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.alter_column('RoleID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('Type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('Session', schema=None) as batch_op:
        batch_op.alter_column('SessionID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('SessionDateTime',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('Description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('Location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'SessionType', ['SessionTypeID'], ['SessionTypeID'])
        batch_op.create_foreign_key(None, 'Groups', ['GroupID'], ['GroupID'])

    with op.batch_alter_table('SessionType', schema=None) as batch_op:
        batch_op.alter_column('SessionTypeID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('Name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('StudentGroups', schema=None) as batch_op:
        batch_op.alter_column('StudentID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('GroupID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Role', ['RoleID'], ['RoleID'])
        batch_op.create_foreign_key(None, 'User', ['StudentID'], ['StudentID'])
        batch_op.create_foreign_key(None, 'Groups', ['GroupID'], ['GroupID'])

    with op.batch_alter_table('Unit', schema=None) as batch_op:
        batch_op.alter_column('UnitCode',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('UnitName',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('FacultyID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Faculty', ['FacultyID'], ['FacultyID'])

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Firstname', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('Lastname', sa.String(length=50), nullable=False))
        batch_op.alter_column('Username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('Password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('Course',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('Email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('Birthday',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('Birthday',
               existing_type=sa.DateTime(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('Email',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('Course',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('Password',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('Username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('Lastname')
        batch_op.drop_column('Firstname')

    with op.batch_alter_table('Unit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Faculty', ['FacultyID'], ['FacultyID'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('FacultyID',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('UnitName',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('UnitCode',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('StudentGroups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Role', ['RoleID'], ['RoleID'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'User', ['StudentID'], ['StudentID'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Groups', ['GroupID'], ['GroupID'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.alter_column('GroupID',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('StudentID',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('SessionType', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('SessionTypeID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Groups', ['GroupID'], ['GroupID'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'SessionType', ['SessionTypeID'], ['SessionTypeID'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.alter_column('Location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('Description',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('SessionDateTime',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('SessionID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Role', schema=None) as batch_op:
        batch_op.alter_column('Type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('RoleID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'GroupType', ['GroupTypeID'], ['GroupTypeID'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'Unit', ['UnitID'], ['UnitID'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('GroupName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('CreationDate',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_DATE)'))
        batch_op.alter_column('Description',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('MaxMembers')

    with op.batch_alter_table('GroupType', schema=None) as batch_op:
        batch_op.alter_column('Type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('Faculty', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
